pipeline {
    agent any

    environment {
        AWS_ACCOUNT_ID   = "562404438689"
        AWS_REGION       = "us-east-1"
        ECR_REPOSITORY   = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

        BACKEND_REPO     = "starbucks-backend"
        FRONTEND_REPO    = "starbucks-frontend"

        IMAGE_TAG        = "${BUILD_NUMBER}"
        HELM_CHART_PATH  = "./my-chart"
    }

    stages {

        stage("Git Clone") {
            steps {
                git branch: 'main',
                    url: 'https://github.com/gopi-ganesan/starbucks-app.git',
                    credentialsId: 'github-creds'
            }
        }

        stage("Run Tests") {
            steps {
                sh 'npm test || true'
            }
        }

        stage('SonarQube Scan') {
            steps {
                script {
                    def scannerHome = tool 'sonar-scanner'
                    withSonarQubeEnv('sonar-server') {
                        withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                            sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=starbucks-app \
                            -Dsonar.sources=. \
                            -Dsonar.login=sqp_d502187ad60cdd5661fd9c538fb3903eb3a7baea
                            """
                        }
                    }
                }
            }
        }
        stage('Quality Check') {
            steps {
                script {
                    try {
                        timeout(time: 1, unit: 'MINUTES') {
                        waitForQualityGate abortPipeline: false
                        }
                    } catch (err) {
                        echo "Skipping Quality Gate due to timeout"
                    }
                }
            }
        }
        stage('Build Docker Images') {
            steps {
                dir('starbucks-app-main') {
                    sh "docker build -t starbucks-backend ./backend"
                    sh "docker build -t starbucks-frontend ./frontend"
                }
            }
        }

        stage('Login to ECR') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials']]) {
                    sh """
                    aws ecr get-login-password --region ${AWS_REGION} | \
                    docker login --username AWS --password-stdin ${ECR_REPOSITORY}
                    """
                }
            }
        }

        stage('Push Images to ECR') {
            steps {
                sh """
                docker tag starbucks-backend ${ECR_REPOSITORY}/${BACKEND_REPO}:${IMAGE_TAG}
                docker push ${ECR_REPOSITORY}/${BACKEND_REPO}:${IMAGE_TAG}

                docker tag starbucks-frontend ${ECR_REPOSITORY}/${FRONTEND_REPO}:${IMAGE_TAG}
                docker push ${ECR_REPOSITORY}/${FRONTEND_REPO}:${IMAGE_TAG}
                """
            }
        }
        stage('Update Helm Values') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'github-creds',
                    usernameVariable: 'GITHUB_USERNAME',
                    passwordVariable: 'GITHUB_PASSWORD'
                    )]) {
                    sh """
                        # git clone \
                        #https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/gopi-ganesan/argocd-starbucks.git \
                        # argocd-starbucks
                        cd argocd-starbucks
                        git remote set-url origin \
                        https://\$GITHUB_USERNAME:\$GITHUB_PASSWORD@github.com/gopi-ganesan/argocd-starbucks.git
                        git fetch origin
                        git reset --hard origin/main
                        sed -i "s|tag:.*|tag: ${IMAGE_TAG}|g" Helm/my-chart/values.yaml
                        grep "tag:" Helm/my-chart/values.yaml
                        git config user.name "\$GITHUB_USERNAME"
                        git config user.email "devops@example.com"
                        git add Helm/my-chart/values.yaml
                        git commit -m "ci: update image tag to ${IMAGE_TAG} [skip ci]" || \
                        echo "Nothing to commit"
                        git pull --rebase origin main
                        git push origin main
                    """
                }
            }
        }
    }
}