backend:
  image: 562404438689.dkr.ecr.us-east-1.amazonaws.com/starbucks-backend
  name: starbucks-backend
  pullPolicy:  Always
  namespace: starbucks-ns
  app: starbucks-backend
  tag: '39'
  replicas: 2
  port: 5000
  nodePort: 30500
  targetPort: 5000
  path: /health

frontend:
  image: 562404438689.dkr.ecr.us-east-1.amazonaws.com/starbucks-frontend
  tag: '39'
  name: starbucks-frontend
  pullPolicy:  Always
  namespace: starbucks-ns
  app: starbucks-frontend
  port: 80
  replicas: 2
  targetPort: 80
  nodePort: 30080
  path: /

mongoExpress:
  name: mongo-express
  image: mongo-express:1.0.2-20-alpine3.19
  namespace: starbucks-ns
  app: mongo-express
  containerPort: 8081
  port: 8081
  nodePort: 30083
  targetPort: 8081
  replicas: 2

mongodb:
  name: mongodb-starbucks-statefulset
  serviceName: mongodb-sc
  namespace: starbucks-ns
  replicas: 2
  app: mongodb
  image: mongo:4.4-focal
  port: 27017
  database: starbucks

secret:
  name: mongo-secret
  namespace: starbucks-ns
  app: mongo-express
  mongoUser: YWRtaW4K
  mongoPassword: cGFzc3dvcmQxMjMK

ingress:
  name: starbucks-ingress
  namespace: starbucks-ns
  ingressClassName: alb
  alb.ingress.kubernetes.io/scheme: internet-facing
  alb.ingress.kubernetes.io/target-type: ip

