apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.secret.namespace }}
  labels:
    app: {{ .Values.secret.app }}
type: Opaque
data:
  mongo-root-username: {{ .Values.secret.mongoUser | b64enc }}
  mongo-root-password: {{ .Values.secret.mongoPassword | b64enc }}
